DEF_DIF_OPR(ADD, "+",   4,  true, false)
DEF_DIF_OPR(SUB, "-",   4,  true, false)
DEF_DIF_OPR(DIV, "/",   3,  true, false)
DEF_DIF_OPR(MUL, "*",   3,  true, false)
DEF_DIF_OPR(POW, "^",   1,  true, false)

DEF_DIF_OPR(LOG, "log", 9, false,  true)
DEF_DIF_OPR(LN,  "ln",  9, false,  true)
DEF_DIF_OPR(DIF, "dif", 9, false,  true)

DEF_DIF_OPR(SIN, "sin", 9, false,  true)
DEF_DIF_OPR(COS, "cos", 9, false,  true)
DEF_DIF_OPR(TAN, "tan", 9, false,  true)